spring.application.name=ocr_project

server.port=${PORT:8080}
server.address=0.0.0.0

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:25102/railway?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=epgRivakyHpHsEpGzfiWvFzWzesrqHfw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# TESSERACT
# ===============================
tesseract.datapath=/usr/share/tesseract-ocr/4.00/tessdata

# ===============================
# AWS CONFIGURATION
# ===============================
amazon.region=ap-south-1
amazon.url=https://s3.amazonaws.com
aws.s3.bucket.qaclide=clide-qaclide-2020-10-31-12-10-48
